name: Publish New Release

on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  publish:
    name: Publish New Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Use Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies And Compile TS
        run: yarn

      - name: Configure Git
        run: git config --global user.name "Rayana Shiba" && git config --global user.email "rayana@tealstreet.io"

      - name: Update package version
        run: yarn version --new-version ${{ github.event.release.tag_name }}

      - name: Push Version Changes To GitHub
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
